import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#e9a771",
        "surface-dim": "#131313",
        "inverse-on-surface": "#313030",
        "on-primary-fixed-variant": "#6e3900",
        "on-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "on-surface-variant": "#ddc1ae",
        "primary-fixed": "#ffdcc3",
        "on-primary-fixed": "#2f1500",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#c7e7ff",
        "surface-container-high": "#2a2a2a",
        "primary-container": "#ff8c00",
        "on-background": "#e5e2e1",
        background: "#131313",
        "outline-variant": "#564334",
        "on-error": "#690005",
        "on-tertiary-fixed": "#001e2e",
        "tertiary-fixed-dim": "#85cfff",
        "secondary-container": "#6a3b0f",
        "secondary-fixed-dim": "#fdb881",
        "secondary-fixed": "#ffdcc3",
        "on-secondary": "#4d2600",
        "inverse-primary": "#904d00",
        "surface-container": "#201f1f",
        "surface-bright": "#393939",
        "surface-container-low": "#1c1b1b",
        tertiary: "#85cfff",
        surface: "#131313",
        "tertiary-container": "#00b5fc",
        "surface-tint": "#ffb77d",
        "on-tertiary-container": "#004360",
        primary: "#ffb77d",
        secondary: "#fdb881",
        "on-secondary-fixed": "#2f1500",
        "on-error-container": "#ffdad6",
        outline: "#a48c7a",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "primary-fixed-dim": "#ffb77d",
        "on-tertiary": "#00344c",
        "surface-container-highest": "#353534",
        "on-primary-container": "#623200",
        "on-primary": "#4d2600",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#6a3b0f",
        "on-tertiary-fixed-variant": "#004c6c",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
